// AUTO-GENERATED by scripts/build-static.mjs — do not edit by hand.
// Re-run `node scripts/build-static.mjs` to update after adding/removing topics.
//
// Strategy:
//   Install  — pre-cache every file in PRECACHE_URLS (shell + all topic JS
//               modules + all static pages) so the site works fully offline
//               from the first visit, not just after visiting each page.
//   Activate — delete any old caches from previous builds, claim all clients
//               immediately so the new SW takes effect without a reload.
//   Fetch    — cache-first for pre-cached assets (they're versioned by the
//               CACHE_VERSION string); network-first for everything else.
//   Update   — when a new SW installs and is waiting, postMessage all open
//               clients so app.js can show a non-intrusive "update available"
//               banner. The banner's "Reload" button sends SKIP_WAITING back,
//               which triggers activate and a page reload.

const CACHE_VERSION = 'v-7a25a8ah';
const CACHE_NAME = `csharp-concepts-${CACHE_VERSION}`;

const PRECACHE_URLS = [
  "./",
  "./index.html",
  "./manifest.json",
  "./css/style.css",
  "./js/highlight.js",
  "./js/app.js",
  "./js/quiz.js",
  "./js/topics/manifest.js",
  "./js/topics/search-index.js",
  "./js/topics/tracks.js",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/maskable-192.png",
  "./icons/maskable-512.png",
  "./icons/apple-touch-icon-180.png",
  "./js/topics/fundamentals/variables-types.js",
  "./js/topics/fundamentals/operators.js",
  "./js/topics/fundamentals/control-flow.js",
  "./js/topics/fundamentals/loops.js",
  "./js/topics/fundamentals/arrays-collections.js",
  "./js/topics/fundamentals/structs.js",
  "./js/topics/fundamentals/enums.js",
  "./js/topics/fundamentals/tuples-deconstruction.js",
  "./js/topics/fundamentals/methods-parameters.js",
  "./js/topics/fundamentals/type-casting.js",
  "./js/topics/fundamentals/string-interpolation.js",
  "./js/topics/fundamentals/nullable-value-types.js",
  "./js/topics/fundamentals/boxing-unboxing.js",
  "./js/topics/oop/classes-objects.js",
  "./js/topics/oop/inheritance.js",
  "./js/topics/oop/interfaces.js",
  "./js/topics/oop/polymorphism.js",
  "./js/topics/oop/encapsulation.js",
  "./js/topics/oop/abstract-classes.js",
  "./js/topics/oop/static-members.js",
  "./js/topics/oop/indexers.js",
  "./js/topics/oop/operator-overloading.js",
  "./js/topics/oop/object-equality.js",
  "./js/topics/oop/sealed.js",
  "./js/topics/oop/object-initializers.js",
  "./js/topics/oop/method-overloading.js",
  "./js/topics/intermediate/generics.js",
  "./js/topics/intermediate/delegates-events.js",
  "./js/topics/intermediate/linq.js",
  "./js/topics/intermediate/exceptions.js",
  "./js/topics/intermediate/extension-methods.js",
  "./js/topics/intermediate/idisposable-using.js",
  "./js/topics/intermediate/iterators-yield.js",
  "./js/topics/intermediate/attributes.js",
  "./js/topics/intermediate/reflection.js",
  "./js/topics/intermediate/dependency-injection.js",
  "./js/topics/intermediate/regular-expressions.js",
  "./js/topics/intermediate/json-serialization.js",
  "./js/topics/intermediate/unit-testing.js",
  "./js/topics/intermediate/solid-principles.js",
  "./js/topics/intermediate/clean-architecture.js",
  "./js/topics/intermediate/memory-management.js",
  "./js/topics/intermediate/performance-tips.js",
  "./js/topics/async/async-await.js",
  "./js/topics/async/tpl.js",
  "./js/topics/async/threading-basics.js",
  "./js/topics/async/cancellation-token.js",
  "./js/topics/async/async-streams.js",
  "./js/topics/async/semaphore-slim.js",
  "./js/topics/async/channels.js",
  "./js/topics/modern-dotnet/records.js",
  "./js/topics/modern-dotnet/pattern-matching.js",
  "./js/topics/modern-dotnet/nullable-reference-types.js",
  "./js/topics/modern-dotnet/file-scoped-namespaces.js",
  "./js/topics/modern-dotnet/raw-string-literals.js",
  "./js/topics/modern-dotnet/generic-math.js",
  "./js/topics/modern-dotnet/init-only-properties.js",
  "./js/topics/modern-dotnet/top-level-statements.js",
  "./js/topics/csharp-latest/primary-constructors.js",
  "./js/topics/csharp-latest/collection-expressions.js",
  "./js/topics/csharp-latest/required-members.js",
  "./js/topics/csharp-latest/params-collections.js",
  "./js/topics/csharp-latest/field-keyword.js",
  "./js/topics/csharp-latest/null-conditional-assignment.js",
  "./js/topics/csharp-latest/extension-members.js",
  "./js/topics/csharp-latest/lock-object.js",
  "./js/topics/patterns/singleton.js",
  "./js/topics/patterns/factory.js",
  "./js/topics/patterns/observer.js",
  "./js/topics/patterns/strategy.js",
  "./js/topics/patterns/repository.js",
  "./js/topics/patterns/builder.js",
  "./js/topics/patterns/decorator.js",
  "./js/topics/patterns/adapter.js",
  "./js/topics/patterns/command.js",
  "./js/topics/aspnet/middleware.js",
  "./js/topics/aspnet/minimal-apis.js",
  "./js/topics/aspnet/authentication.js",
  "./js/topics/aspnet/jwt.js",
  "./js/topics/aspnet/background-services.js",
  "./js/topics/aspnet/caching.js",
  "./js/topics/aspnet/logging.js",
  "./js/topics/aspnet/configuration.js",
  "./js/topics/aspnet/options-pattern.js",
  "./topics/variables-types/index.html",
  "./topics/operators/index.html",
  "./topics/control-flow/index.html",
  "./topics/loops/index.html",
  "./topics/arrays-collections/index.html",
  "./topics/structs/index.html",
  "./topics/enums/index.html",
  "./topics/tuples-deconstruction/index.html",
  "./topics/methods-parameters/index.html",
  "./topics/type-casting/index.html",
  "./topics/string-interpolation/index.html",
  "./topics/nullable-value-types/index.html",
  "./topics/boxing-unboxing/index.html",
  "./topics/classes-objects/index.html",
  "./topics/inheritance/index.html",
  "./topics/interfaces/index.html",
  "./topics/polymorphism/index.html",
  "./topics/encapsulation/index.html",
  "./topics/abstract-classes/index.html",
  "./topics/static-members/index.html",
  "./topics/indexers/index.html",
  "./topics/operator-overloading/index.html",
  "./topics/object-equality/index.html",
  "./topics/sealed/index.html",
  "./topics/object-initializers/index.html",
  "./topics/method-overloading/index.html",
  "./topics/generics/index.html",
  "./topics/delegates-events/index.html",
  "./topics/linq/index.html",
  "./topics/exceptions/index.html",
  "./topics/extension-methods/index.html",
  "./topics/idisposable-using/index.html",
  "./topics/iterators-yield/index.html",
  "./topics/attributes/index.html",
  "./topics/reflection/index.html",
  "./topics/dependency-injection/index.html",
  "./topics/regular-expressions/index.html",
  "./topics/json-serialization/index.html",
  "./topics/unit-testing/index.html",
  "./topics/solid-principles/index.html",
  "./topics/clean-architecture/index.html",
  "./topics/memory-management/index.html",
  "./topics/performance-tips/index.html",
  "./topics/async-await/index.html",
  "./topics/tpl/index.html",
  "./topics/threading-basics/index.html",
  "./topics/cancellation-token/index.html",
  "./topics/async-streams/index.html",
  "./topics/semaphore-slim/index.html",
  "./topics/channels/index.html",
  "./topics/records/index.html",
  "./topics/pattern-matching/index.html",
  "./topics/nullable-reference-types/index.html",
  "./topics/file-scoped-namespaces/index.html",
  "./topics/raw-string-literals/index.html",
  "./topics/generic-math/index.html",
  "./topics/init-only-properties/index.html",
  "./topics/top-level-statements/index.html",
  "./topics/primary-constructors/index.html",
  "./topics/collection-expressions/index.html",
  "./topics/required-members/index.html",
  "./topics/params-collections/index.html",
  "./topics/field-keyword/index.html",
  "./topics/null-conditional-assignment/index.html",
  "./topics/extension-members/index.html",
  "./topics/lock-object/index.html",
  "./topics/singleton/index.html",
  "./topics/factory/index.html",
  "./topics/observer/index.html",
  "./topics/strategy/index.html",
  "./topics/repository/index.html",
  "./topics/builder/index.html",
  "./topics/decorator/index.html",
  "./topics/adapter/index.html",
  "./topics/command/index.html",
  "./topics/middleware/index.html",
  "./topics/minimal-apis/index.html",
  "./topics/authentication/index.html",
  "./topics/jwt/index.html",
  "./topics/background-services/index.html",
  "./topics/caching/index.html",
  "./topics/logging/index.html",
  "./topics/configuration/index.html",
  "./topics/options-pattern/index.html",
  "./tracks/getting-started/index.html",
  "./tracks/async-deep-dive/index.html",
  "./tracks/design-patterns-essentials/index.html",
  "./tracks/modern-csharp/index.html",
  "./tracks/interview-prep/index.html",
  "./tracks/aspnet-core-essentials/index.html"
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then(cache => cache.addAll(PRECACHE_URLS))
      // Don't skipWaiting automatically — wait for the user to confirm the
      // update via the "Reload to update" banner (see postMessage below).
      // This prevents in-progress quiz sessions from being disrupted.
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(
        keys
          .filter(k => k.startsWith('csharp-concepts-') && k !== CACHE_NAME)
          .map(k => caches.delete(k))
      )
    ).then(() => self.clients.claim())
  );
});

// Tell all open tabs there's a new version waiting — app.js listens for
// this and shows the update banner.
self.addEventListener('install', () => {
  self.clients.matchAll({ includeUncontrolled: true, type: 'window' })
    .then(clients => clients.forEach(c => c.postMessage({ type: 'SW_WAITING' })));
});

// app.js sends SKIP_WAITING when the user clicks "Reload to update".
self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || !req.url.startsWith(self.location.origin)) return;

  const url = new URL(req.url);
  const pathname = url.pathname;

  // Cache-first for pre-cached assets (JS modules, CSS, static pages).
  // These are versioned by CACHE_VERSION so stale responses are never served
  // after a deploy — the old cache is deleted on activate.
  const isPrecached = PRECACHE_URLS.some(u => {
    const p = new URL(u, self.location.href).pathname;
    return p === pathname;
  });

  if (isPrecached) {
    event.respondWith(
      caches.match(req).then(cached => cached || fetch(req).then(res => {
        caches.open(CACHE_NAME).then(c => c.put(req, res.clone()));
        return res;
      }))
    );
    return;
  }

  // Network-first for everything else (topic JS modules loaded dynamically
  // after a new topic is added but before the SW is updated, external fonts).
  event.respondWith(
    fetch(req)
      .then(res => {
        caches.open(CACHE_NAME).then(c => c.put(req, res.clone()));
        return res;
      })
      .catch(() =>
        caches.match(req).then(cached => {
          if (cached) return cached;
          if (req.mode === 'navigate') return caches.match('./index.html');
        })
      )
  );
});
