// Auto-generated by build-static.mjs — do not edit by hand.
export const SEARCH_INDEX = [
  {
    "id": "variables-types",
    "title": "Variables & Types",
    "category": "",
    "tagline": "C# is statically typed — every variable has a type known at compile time.",
    "keywords": "Every variable in C# is declared with a type, and the compiler checks that type at build time rather than at runtime. This catches a whole category of bugs before your program ever runs. You can either name the type explicitly ( int , string , bool ) or let the compiler infer it with var — the type is still fixed once assigned, var just saves you typing it out. C# distinguishes value types (like int , double , struct ), which hold their data directly, from reference types (like string , class ), which hold a pointer to data elsewhere. This distinction affects how copying and comparison behave. var infers the type at compile time — it is not dynamic typing Value types are copied by value; reference types are copied by reference Nullable value types use a ? suffix, e.g. int? Using var and as"
  },
  {
    "id": "operators",
    "title": "Operators & Expressions",
    "category": "",
    "tagline": "Arithmetic, logical, and null-handling operators.",
    "keywords": "C# supports the usual arithmetic and comparison operators, plus a few that make null-handling much less verbose. The null-coalescing operator ( ?? ) supplies a fallback value when the left side is null, and ??= assigns only if the variable is currently null. The null-conditional operator ( ?. ) short-circuits to null instead of throwing when you access a member on a null reference — extremely common when working with data that may be missing. ?? returns a fallback when the left operand is null ?. safely navigates a possibly-null reference Compound assignment operators (+=, -=) mutate in place Confusing = (assignment) with == (equality check) inside conditions Expecting & and | to short-circuit — use && and || for short-circuit evaluation Forgetting operator precedence: use parentheses to m"
  },
  {
    "id": "control-flow",
    "title": "Control Flow",
    "category": "",
    "tagline": "if/else, switch statements, and switch expressions.",
    "keywords": "Beyond the familiar if / else if / else , modern C# has a switch expression — a compact, value-producing alternative to the older switch statement. It uses pattern matching, so you can match on types, ranges, and shapes, not just constant values. Switch expressions must be exhaustive or include a discard pattern ( _ ) as a catch-all, which the compiler will warn you about if missing. Switch expressions return a value using => The _ pattern acts as the default/catch-all case Pattern matching can test types and value ranges, not just equality Forgetting break in switch cases — without it, control falls through (except in C# pattern-matching switches) Using if/else chains instead of switch expressions when matching a single variable Missing the default case in a switch, leaving unhandled valu"
  },
  {
    "id": "loops",
    "title": "Loops",
    "category": "",
    "tagline": "for, foreach, while, and do-while.",
    "keywords": "foreach is the idiomatic way to iterate any IEnumerable — arrays, lists, dictionaries — without managing an index. Use a plain for loop when you need the index itself or want to iterate in a non-standard step. while checks its condition before each iteration; do-while checks after, guaranteeing the body runs at least once. foreach cannot modify the collection it is iterating over break exits a loop entirely; continue skips to the next iteration do-while always executes its body at least once Modifying a collection inside a foreach loop — throws InvalidOperationException at runtime Off-by-one errors with for loops: using < vs <= for the boundary condition Using while(true) without a guaranteed exit path, causing an infinite loop"
  },
  {
    "id": "arrays-collections",
    "title": "Arrays & Collections",
    "category": "",
    "tagline": "Fixed-size arrays vs. resizable List<T> and Dictionary<K,V>.",
    "keywords": "Arrays have a fixed length set at creation. List&lt;T&gt; from System.Collections.Generic wraps an array internally but resizes automatically as you add items, making it the default choice for most collections. Dictionary&lt;TKey, TValue&gt; stores key-value pairs with near-constant-time lookups, ideal whenever you need to look something up by a unique key rather than scan a list. List<T> grows dynamically; arrays do not Dictionary<K,V> lookups are much faster than scanning a List for a match Both implement IEnumerable<T>, so foreach works on either Accessing an index that doesn't exist — always check Count/Length or use TryGetValue Confusing List<T> (resizable) with arrays (fixed size) — most code should prefer List<T> Adding to a collection while iterating over it — collect changes and a"
  },
  {
    "id": "structs",
    "title": "Structs",
    "category": "",
    "tagline": "Value types for small, self-contained data.",
    "keywords": "A struct is a value type — assigning or passing one copies its data rather than sharing a reference. That makes structs a good fit for small, short-lived values like a point or a money amount, where copy semantics are exactly what you want and avoiding a heap allocation matters. Unlike classes, structs can't inherit from another class or struct (though they can implement interfaces), and every field must be assigned before the constructor finishes. Structs are copied by value; classes are copied by reference Best for small, short-lived data where copy overhead is cheap Structs can implement interfaces but cannot inherit from a class or another struct Mutating a struct through a readonly field or property — the compiler silently copies it first Making structs too large — structs are copied "
  },
  {
    "id": "enums",
    "title": "Enums",
    "category": "",
    "tagline": "A closed, named set of constant values.",
    "keywords": "An enum defines a type with a fixed set of named values, making code that would otherwise rely on magic numbers or raw strings self-documenting and type-checked by the compiler. Under the hood, an enum is backed by an integer type ( int by default). Combine values as bit flags with the [Flags] attribute when a variable needs to represent more than one option at once, and use Enum.Parse to convert a string into an enum value at runtime. Backed by an integer type by default (int); can be changed, e.g. : byte [Flags] lets enum values be combined with bitwise OR Enum.Parse / TryParse convert strings to enum values at runtime Casting an arbitrary integer to an enum — use Enum.IsDefined to validate first Using enums for bit flags without [Flags] and powers of two — bitwise operations won't work "
  },
  {
    "id": "tuples-deconstruction",
    "title": "Tuples & Deconstruction",
    "category": "",
    "tagline": "Group a few values together without declaring a class.",
    "keywords": "Value tuples let you return or group multiple values with named elements without declaring a dedicated type — handy for small, internal groupings that don't warrant a full class or record. The syntax (string Name, int Age) gives each element a readable name instead of relying on .Item1 , .Item2 . Deconstruction unpacks a tuple — or any type with a matching Deconstruct method, including records — into separate variables in one statement. (string Name, int Age) syntax gives tuple elements meaningful names Deconstruction works on tuples, records, and any type with a matching Deconstruct method Prefer a record over a tuple once the grouping has real behavior or is used widely Using ValueTuple for public APIs — named properties on a class or record are far more readable Forgetting that tuple el"
  },
  {
    "id": "methods-parameters",
    "title": "Methods & Parameters",
    "category": "",
    "tagline": "ref, out, in, optional parameters, and overloading.",
    "keywords": "Parameters pass by value by default — the method gets its own copy. ref lets a method modify the caller's variable directly, out is similar but doesn't require the caller to initialize the variable first (it must be assigned inside the method), and in passes by reference as read-only, avoiding a copy for large structs without allowing mutation. Optional parameters let callers omit arguments that have a default value, and method overloading lets you define several methods with the same name distinguished by their parameter list. ref requires the caller’s variable to already have a value; out does not, but must be assigned inside the method in passes by reference but prevents the method from modifying the argument Overloads are distinguished by parameter type/count, not by return type alone "
  },
  {
    "id": "type-casting",
    "title": "Type Casting & Conversion",
    "category": "",
    "tagline": "Implicit vs. explicit conversion, and safely checking types with is/as.",
    "keywords": "Conversions that can't lose data ( int to long ) happen implicitly . Conversions that might lose data ( double to int ) require an explicit cast — you're telling the compiler you accept the risk. The as operator attempts a reference conversion and returns null on failure instead of throwing. is checks a type without converting at all, and can bind the result to a new variable in the same expression. Implicit conversions never lose data; explicit casts might, so the compiler requires you to opt in as returns null on failure instead of throwing an exception is pattern-matches a type and can bind the result to a new variable in one step Using a hard cast (MyType)obj when it might fail — prefer as + null check or is pattern matching Confusing as (returns null on failure) with a direct cast (th"
  },
  {
    "id": "string-interpolation",
    "title": "String Interpolation & Formatting",
    "category": "",
    "tagline": "Building readable strings with $\"...\" and format specifiers.",
    "keywords": "String interpolation ( $\"...\" ) embeds expressions directly inside a string literal, replacing verbose string.Format calls or concatenation. Any expression can go inside the braces, not just a variable name. Format specifiers after a colon control exactly how a value renders — :C for currency, :F2 for two decimal places, :yyyy-MM-dd for a date pattern. Any expression can go inside the { } of an interpolated string, not just a variable Format specifiers (:C, :F2, :N0, :yyyy-MM-dd) control the exact rendering Raw string literals (\"\"\"...\"\"\"), covered separately, pair well with interpolation for multi-line text Using string concatenation in a loop — use StringBuilder or string.Join for many concatenations Forgetting culture sensitivity: $\"{price}\" uses the current culture; use .ToString(\"C\", c"
  },
  {
    "id": "nullable-value-types",
    "title": "Nullable Value Types",
    "category": "",
    "tagline": "Let value types represent \"no value\" without a sentinel.",
    "keywords": "Value types like int or bool can't normally be null — they always hold a value. Nullable&lt;T&gt; (written as T? , e.g. int? ) wraps a value type so it can also represent \"no value\", which is common for things like an optional age or a database column that allows NULL. Use .HasValue and .Value to check and unwrap safely, the ?? null-coalescing operator to supply a default, or pattern matching. Accessing .Value on a null instance throws InvalidOperationException . int? is shorthand for Nullable<int>; works for any struct, not just int HasValue/Value or ?? are the safe ways to read a nullable value type Distinct from nullable reference types, which apply to classes, not structs Accessing .Value without checking .HasValue first — throws InvalidOperationException if null Confusing Nullable<T> "
  },
  {
    "id": "boxing-unboxing",
    "title": "Boxing & Unboxing",
    "category": "",
    "tagline": "The hidden cost of treating a value type as an object.",
    "keywords": "Boxing copies a value type (like int or a struct ) onto the heap and wraps it in an object , so it can be used wherever a reference type is expected. Unboxing copies it back out into a value-type variable. Both are implicit and easy to trigger accidentally — adding an int to a non-generic ArrayList , for example — and each one allocates memory and copies data. Generic collections like List&lt;int&gt; avoid this entirely, which is one reason they replaced non-generic collections. Boxing allocates a heap object to hold a copy of a value type Unboxing requires an exact type match or it throws InvalidCastException Generics (List<T> vs ArrayList) avoid boxing and its allocation overhead Adding value types to non-generic collections (ArrayList, Hashtable) — each add boxes the value Unboxing to t"
  },
  {
    "id": "ref-out-in",
    "title": "ref, out & in Parameters",
    "category": "",
    "tagline": "Three keywords for passing by reference — each with a different contract.",
    "keywords": "By default, C# passes arguments by value — the method gets a copy. The ref , out , and in keywords pass the variable itself (by reference), so the method can read or write the caller's original storage location. ref — two-way: the caller must initialise the variable first; the method may read and write it. out — write-only contract: the caller need not initialise; the method must assign before returning. Used when a method produces multiple outputs ( int.TryParse ). in (C# 7.2) — read-only reference: the method receives a reference but cannot modify the value. Avoids copying large structs without risk of accidental mutation. ref: caller initialises first; method can read and write out: caller need not initialise; method must assign before returning in: read-only reference; prevents copying"
  },
  {
    "id": "const-readonly",
    "title": "const vs readonly",
    "category": "",
    "tagline": "const is a compile-time literal; readonly is set once at construction time.",
    "keywords": "const must be assigned a compile-time constant (a literal or an expression of literals). The compiler inlines the value everywhere it is used — the field itself does not exist at runtime. This makes const fast but inflexible: changing its value is a breaking change for any assembly that was compiled against it. readonly is evaluated at runtime. It can be set in a constructor (including static constructors), so it can hold complex values like new List&lt;string&gt; . static readonly is the correct pattern for constants that are not primitive literals or that might change between deployments. const: compile-time only; limited to primitive types and string; inlined by the compiler readonly: set once, at field initialisation or in a constructor; any type allowed static readonly is the safer ch"
  },
  {
    "id": "classes-objects",
    "title": "Classes & Objects",
    "category": "",
    "tagline": "The blueprint (class) and the instance (object).",
    "keywords": "A class defines the shape of something — its fields, properties, and methods. An object is a concrete instance created from that blueprint with new . Properties (using get / set ) expose a class's state while letting you control how it's read or written. Constructors initialize a new object's state; C# also supports object initializer syntax to set public properties inline at creation time. Properties can have different access levels for get vs set Object initializers set properties without a custom constructor this refers to the current instance inside a method Forgetting to initialise fields — reference type fields default to null, not an empty object Making everything public — prefer private fields with properties to control access Creating very large classes — split responsibilities wh"
  },
  {
    "id": "inheritance",
    "title": "Inheritance",
    "category": "",
    "tagline": "Sharing behavior through a base class.",
    "keywords": "A class can inherit from a single base class using a colon, gaining its public and protected members. override lets a derived class replace a base method marked virtual , while base.Method() calls the original implementation from within the override. C# supports single inheritance only — a class can extend one base class, but implement multiple interfaces (see the Interfaces topic). Only virtual/abstract members can be overridden base.Method() invokes the parent version explicitly C# has single class inheritance, but multiple interface implementation Overusing inheritance for code reuse — prefer composition when the 'is-a' relationship isn't real Forgetting to call base() in a constructor, leaving the base class uninitialised Sealing a class too early, or never sealing it — be intentional "
  },
  {
    "id": "interfaces",
    "title": "Interfaces",
    "category": "",
    "tagline": "A contract for what a type can do, not how.",
    "keywords": "An interface declares members without implementing them — it's a contract. Any class or struct that implements the interface must provide the implementation. A single class can implement any number of interfaces, which is how C# achieves multiple-inheritance-like flexibility. Interfaces are the backbone of dependency injection and testability: code that depends on ILogger rather than a concrete FileLogger can be swapped or mocked freely. A class can implement multiple interfaces Interfaces enable loose coupling and easier unit testing Since C# 8, interfaces can include default method implementations Implementing an interface but making methods throw NotImplementedException — violates the Liskov principle Creating interfaces with too many members — prefer small, focused interfaces (Interfac"
  },
  {
    "id": "polymorphism",
    "title": "Polymorphism",
    "category": "",
    "tagline": "One interface, many implementations.",
    "keywords": "Polymorphism means you can treat different concrete types uniformly through a shared base type or interface. A List&lt;IShape&gt; can hold circles, squares, and triangles, and calling .Area() on each dispatches to the correct implementation at runtime — this is runtime (dynamic) dispatch . This is what makes code extensible: you can add a new shape type without touching the code that iterates over shapes. Runtime dispatch picks the correct override based on the actual object type Enables adding new types without modifying existing consuming code Works through both base classes and interfaces Forgetting virtual on the base method — without it, the derived method hides rather than overrides Using new instead of override — the method is hidden, not overridden, and virtual dispatch won't reach"
  },
  {
    "id": "encapsulation",
    "title": "Encapsulation",
    "category": "",
    "tagline": "Controlling access with public, private, and protected.",
    "keywords": "Encapsulation means hiding internal state and exposing only what's needed. C# controls this with access modifiers: private (this class only), protected (this class and subclasses), internal (this assembly), and public (anyone). A common pattern is a private backing field with a public property that validates input before allowing a change, keeping the object always in a valid state. private fields with public properties let you validate before mutating state protected exposes members to subclasses but not the outside world Encapsulation reduces the surface area that other code can break Exposing mutable collections as public properties — callers can modify the internal state directly Making fields public instead of using properties — bypasses validation and future-proofing Using public set"
  },
  {
    "id": "abstract-classes",
    "title": "Abstract Classes",
    "category": "",
    "tagline": "Partial blueprints that can’t be instantiated directly.",
    "keywords": "An abstract class can mix implemented members with abstract members that have no body — subclasses are required to implement them. Unlike an interface, an abstract class can hold shared state and constructor logic, making it a good fit when related types share real behavior, not just a contract. You cannot create an instance of an abstract class directly with new ; it only exists to be extended. Abstract classes can have both implemented and abstract members Cannot be instantiated directly — only through a derived class Choose abstract class over interface when subclasses share real state or logic Making a class abstract when an interface would do — abstract classes consume the single base-class slot Putting too much concrete logic in an abstract class — makes subclasses harder to test in "
  },
  {
    "id": "static-members",
    "title": "Static Members & Classes",
    "category": "",
    "tagline": "Belongs to the type itself, not to any instance.",
    "keywords": "A static member belongs to the type, not to any particular object — there's exactly one copy, shared across every use of that type in the program. A static class (like Math or Console ) can't be instantiated at all; it exists purely to group related static functionality. Instance members can freely access static members, but static members can't access instance members without being handed a specific instance to work with. Static fields/state are shared across every part of the program that touches the type Static classes cannot be instantiated and cannot have instance members Instance members can access static members, but not vice versa without an instance Storing mutable state in static fields — it's shared across all threads and requests, causing race conditions Static classes with man"
  },
  {
    "id": "indexers",
    "title": "Indexers",
    "category": "",
    "tagline": "Let your own type be accessed with [] like an array.",
    "keywords": "An indexer lets instances of your class be accessed with array-like bracket syntax ( myObject[key] ) instead of a named method like GetItem(key) . It's how types like List&lt;T&gt; and Dictionary&lt;K,V&gt; support the [] syntax you already use every day. An indexer is defined with the this keyword in place of a method name, and — like a property — can expose both a get and a set accessor. Defined with the this keyword instead of a method name Can be overloaded with different parameter types (e.g. int and string) Supports both get and set, just like a property Not validating the index argument — out-of-range access should throw ArgumentOutOfRangeException, not return null Making indexers do expensive work — callers expect index access to be fast, like array access Exposing internal state b"
  },
  {
    "id": "operator-overloading",
    "title": "Operator Overloading",
    "category": "",
    "tagline": "Define what +, ==, and other operators mean for your own type.",
    "keywords": "C# lets you overload operators like + , - , == , and != for your own types using the operator keyword, so instances can be combined with the same syntax as built-in numeric types. This is especially natural for value-like types such as a Money or Vector struct, where \"adding two of them together\" has an obvious meaning. Use it sparingly — only when the operator's meaning is genuinely unambiguous for the type; overloading + to do something unrelated to addition just confuses readers. Defined as public static methods using the operator keyword If you overload == you should also overload != and override Equals/GetHashCode Use sparingly — only when the operator’s meaning is genuinely obvious for the type Overloading == without also overloading != and overriding Equals/GetHashCode — breaking sy"
  },
  {
    "id": "object-equality",
    "title": "Object Equality",
    "category": "",
    "tagline": "== vs. Equals(), and why overriding one usually means overriding both.",
    "keywords": "For reference types, == compares references by default — are these the exact same object in memory? Equals can be overridden to compare by value instead. Records get this value-based behavior automatically; plain classes don't unless you write it yourself. If you override Equals , you must also override GetHashCode — two objects considered equal must always produce the same hash code, or collections like Dictionary and HashSet will behave incorrectly. Records get value-based Equals/GetHashCode/== automatically; plain classes don’t If you override Equals, you must also override GetHashCode Two objects that are Equal must always return the same GetHashCode Forgetting to override GetHashCode when overriding Equals — objects used as dictionary keys will break Comparing reference types with == "
  },
  {
    "id": "sealed",
    "title": "Sealed Classes & Members",
    "category": "",
    "tagline": "Prevent further inheritance or overriding.",
    "keywords": "Marking a class sealed prevents any other class from inheriting from it — useful once a type's design shouldn't be extended further, and it lets the JIT apply certain optimizations since it knows no override can exist elsewhere. You can also apply sealed override to an individual member in a derived class, locking that one member's implementation in place while still allowing further subclasses of the derived class itself. A sealed class cannot be a base class for any other class sealed override locks in one member’s implementation while leaving the class itself inheritable Common for small, complete value-like types — many built-in .NET types are sealed Sealing every class by default before the design is stable — it prevents extension without modification Forgetting that sealed on a metho"
  },
  {
    "id": "object-initializers",
    "title": "Object Initializers",
    "category": "",
    "tagline": "Set properties right where you construct the object.",
    "keywords": "An object initializer lets you set public properties or fields immediately after construction, in a single expression, without writing a matching constructor overload for every combination of values. It's syntactic sugar: the compiler still calls the constructor first (parameterless unless you specify one), then assigns each property in order. It pairs well with init -only properties when you want the object immutable after that point. Object initializers run after the constructor, assigning properties in order Avoids writing a constructor overload for every combination of properties Works with nested objects and collections too: new Order { Items = { ... } } Using object initializers to bypass validation in the constructor — the constructor runs first, but properties with setters have no "
  },
  {
    "id": "method-overloading",
    "title": "Method Overloading",
    "category": "",
    "tagline": "Same method name, different signatures, resolved at compile time.",
    "keywords": "Method overloading lets a class expose multiple methods with the same name as long as their parameter lists differ — in number, order, or type. The compiler picks which one to call based on the arguments at the call site, so there's no runtime lookup cost. This differs from overriding (which changes behavior of an inherited method with the same signature) — overloading changes the signature itself to offer convenient variations of the same operation. Overloads must differ in parameter type, count, or order — not just return type Resolved at compile time based on the argument types passed in Different from overriding, which keeps the same signature across a hierarchy Creating overloads that differ only in optionality — callers can't tell which one will be called Overloading with params and "
  },
  {
    "id": "generics",
    "title": "Generics",
    "category": "",
    "tagline": "Write one algorithm that works across many types, safely.",
    "keywords": "Generics let you parameterize a class or method by type, so List&lt;T&gt; works identically whether T is int , string , or a custom class — without boxing value types or casting objects, and with full compile-time type checking. Constraints ( where T : IComparable&lt;T&gt; ) restrict what T can be, letting you call members on T that the compiler otherwise couldn't guarantee exist. Generics give type safety without duplicating code per type Constraints (where T : ...) unlock operations on the generic type Avoids boxing/unboxing overhead that untyped collections had Forgetting type constraints — unconstrained T can't call any methods, use where T : IMyInterface Creating unnecessary generic types when the concrete type is always the same at every call site Confusing generic type variance — Li"
  },
  {
    "id": "delegates-events",
    "title": "Delegates & Events",
    "category": "",
    "tagline": "Type-safe references to methods, and the pub/sub pattern built on them.",
    "keywords": "A delegate is a type-safe function pointer — a variable that holds a reference to a method matching a given signature. Action and Func are built-in generic delegate types for the common cases of \"no return value\" and \"returns a value.\" An event wraps a delegate to implement publish/subscribe: a class exposes an event, other code subscribes with += , and the class invokes it when something happens — without the subscribers needing a reference to each other. Action<T> and Func<T,TResult> cover most delegate use cases without a custom delegate type Events restrict outside code to only += and -=, not direct invocation Multiple methods can subscribe to the same event (multicast) Not null-checking an event before invoking — use event?.Invoke() to avoid NullReferenceException Forgetting to unsubs"
  },
  {
    "id": "linq",
    "title": "LINQ",
    "category": "",
    "tagline": "Query collections declaratively, like SQL for in-memory data.",
    "keywords": "LINQ (Language Integrated Query) adds query operators like Where , Select , OrderBy , and GroupBy directly onto any IEnumerable&lt;T&gt; . These are lazily evaluated — nothing runs until you actually enumerate the result, e.g. with foreach or .ToList() . LINQ works identically over in-memory collections, XML, and (via EF Core) SQL databases, which is why it's worth learning early — the same mental model applies everywhere. LINQ queries are lazily evaluated until enumerated Method syntax (.Where().Select()) and query syntax (from...where...select) are equivalent Works over in-memory collections, XML, and EF Core database queries Forgetting that LINQ queries are lazy — the query runs each time you enumerate it, not when you define it Calling .ToList() prematurely and materialising a large se"
  },
  {
    "id": "exceptions",
    "title": "Exception Handling",
    "category": "",
    "tagline": "try/catch/finally and when to throw.",
    "keywords": "C# uses exceptions for error conditions that are exceptional, not for routine control flow. A try block runs code that might fail; matching catch blocks handle specific exception types; finally always runs, making it the right place for cleanup like closing a file. Catch specific exception types before general ones — catching the base Exception type first would swallow everything, hiding bugs you actually want to see. Catch specific exception types before general ones finally always runs, whether or not an exception occurred Prefer exceptions for truly exceptional cases, not expected branching Catching Exception (or worse, catching and swallowing it) instead of a specific exception type Using exceptions for normal control flow — they're expensive and make code harder to read Re-throwing wi"
  },
  {
    "id": "extension-methods",
    "title": "Extension Methods",
    "category": "",
    "tagline": "Add methods to a type you don’t own.",
    "keywords": "Extension methods let you \"add\" a method to an existing type — even one from the .NET framework you can't modify — by defining a static method in a static class where the first parameter is prefixed with this . LINQ itself is implemented entirely as extension methods on IEnumerable&lt;T&gt; , which is why .Where() appears to be a method on every collection type. Defined as static methods in a static class, first param uses this Called as if they were instance methods on the extended type LINQ’s entire operator set is implemented this way Adding extension methods to very broad types (object, string) — they pollute every using context Hiding instance methods with extension methods of the same signature — instance method always wins, causing confusion Putting extension methods in the same nam"
  },
  {
    "id": "idisposable-using",
    "title": "IDisposable & using",
    "category": "",
    "tagline": "Deterministic cleanup for limited or unmanaged resources.",
    "keywords": "Types that hold onto a limited resource — a file handle, a network connection, a database connection — implement IDisposable so callers can release it deterministically, rather than waiting for the garbage collector to eventually get around to it. The using statement guarantees Dispose() runs when the block ends, even if an exception is thrown inside it. A using declaration (no braces) does the same thing, disposing at the end of the enclosing scope instead. Dispose() should be safe to call more than once using ensures Dispose runs even when an exception occurs inside the block A using declaration (no braces) disposes at the end of the enclosing scope Forgetting using on anything that implements IDisposable — file handles, connections, and streams leak Calling Dispose manually and then usi"
  },
  {
    "id": "iterators-yield",
    "title": "Iterators (yield)",
    "category": "",
    "tagline": "Generate a sequence lazily, one item at a time.",
    "keywords": "The yield return keyword lets you write a method that produces an IEnumerable&lt;T&gt; without building the whole collection up front. Each call to the enumerator's MoveNext() resumes the method exactly where it left off, with all local state preserved automatically. This makes it possible to lazily generate expensive or even infinite sequences, since only the items actually consumed are ever computed. yield return produces the next element and pauses the method until the next item is requested The method’s local variables and loop position are preserved between calls automatically Enables infinite sequences, since only the items actually consumed are ever computed Forgetting that yield return is lazy — code before the first yield doesn't run until enumeration starts Wrapping a yield metho"
  },
  {
    "id": "dependency-injection",
    "title": "Dependency Injection",
    "category": "",
    "tagline": "Ask for what you need instead of constructing it yourself.",
    "keywords": "Dependency injection (DI) is a technique where a class declares the services it depends on (usually via constructor parameters) instead of creating them internally with new . Something external — a DI container — is responsible for supplying the right implementation. This decouples code from concrete implementations, making it easy to swap a real service for a test double, and is built directly into ASP.NET Core via IServiceCollection , with common lifetimes of Singleton , Scoped , and Transient . Classes depend on abstractions (interfaces), not concrete implementations A container resolves and supplies dependencies, usually via the constructor ASP.NET Core has DI built in: AddSingleton, AddScoped, AddTransient Injecting a Scoped service into a Singleton — the scoped service is captured an"
  },
  {
    "id": "json-serialization",
    "title": "JSON Serialization",
    "category": "",
    "tagline": "Convert objects to JSON and back with System.Text.Json.",
    "keywords": "System.Text.Json is the built-in serializer for converting .NET objects to and from JSON, replacing the older third-party Newtonsoft.Json for most scenarios. JsonSerializer.Serialize and Deserialize handle the conversion, and attributes like [JsonPropertyName] or options like PropertyNamingPolicy control the shape of the JSON. For high-performance or trimmed/AOT scenarios, source-generated serialization (a JsonSerializerContext ) avoids reflection entirely by generating the (de)serialization code at build time. JsonSerializer.Serialize/Deserialize are the core built-in APIs JsonSerializerOptions controls casing, indentation, and null handling Source-generated contexts avoid reflection for better startup/AOT performance Deserialising into a type with no public setters — the properties stay "
  },
  {
    "id": "unit-testing",
    "title": "Unit Testing",
    "category": "",
    "tagline": "Verify each unit of logic in isolation, fast and repeatably.",
    "keywords": "Unit tests verify a single class or method in isolation — no database, no HTTP, no file system. The most popular framework in .NET is xUnit , which discovers tests by convention: any public class with a [Fact] (single case) or [Theory] (multiple inputs via [InlineData] ) method is a test. Assertions use Assert.Equal , Assert.True , Assert.Throws , etc. Isolating dependencies is done with mocks — test doubles that fake external behaviour. The Moq library is the standard choice: new Mock&lt;IMyService&gt;() creates a mock, .Setup(...).Returns(...) configures it, and .Verify(...) asserts it was called. The Arrange-Act-Assert pattern keeps tests readable: set up, run, check. [Fact] marks a single test; [Theory] with [InlineData] runs it with multiple inputs Mock dependencies with Moq so tests "
  },
  {
    "id": "solid-principles",
    "title": "SOLID Principles",
    "category": "",
    "tagline": "Five principles that keep object-oriented code maintainable as it grows.",
    "keywords": "SOLID is an acronym for five design principles: Single Responsibility (a class should have one reason to change), Open/Closed (open for extension, closed for modification), Liskov Substitution (subtypes must be substitutable for their base types), Interface Segregation (prefer small, focused interfaces), and Dependency Inversion (depend on abstractions, not concretions). They're not rules to follow mechanically, but heuristics that point toward the same underlying goal: loosely coupled, highly cohesive code that can be extended and tested without cascading changes. Violating one principle typically makes another harder to satisfy too — spotting that tension is often the clearest signal a refactor is needed. SRP: one reason to change — split classes when they serve two distinct purposes OCP"
  },
  {
    "id": "memory-management",
    "title": "Memory Management",
    "category": "",
    "tagline": "Understand the GC, the stack vs heap, and how to avoid common leaks.",
    "keywords": ".NET uses a generational garbage collector that automatically reclaims heap memory. Objects are born in Generation 0 ; those that survive a collection are promoted to Gen 1, then Gen 2. Short-lived objects (most objects) are collected cheaply in Gen 0. Long-lived objects (caches, singletons) sit in Gen 2 and are collected rarely — if they grow unbounded, that's a memory leak even under GC. Value types (structs, primitives) live on the stack (or inline in an array) and require no GC at all — they're simply popped when the method returns. Span&lt;T&gt; and ArrayPool&lt;T&gt; are key tools for reducing heap allocations in hot paths. For anything that wraps an unmanaged resource (file handles, sockets), implement IDisposable and use a using statement — the GC does not call Dispose for you. GC "
  },
  {
    "id": "ienumerable-iqueryable",
    "title": "IEnumerable vs IQueryable",
    "category": "",
    "tagline": "IEnumerable filters data in memory; IQueryable translates LINQ to the data source.",
    "keywords": "IEnumerable&lt;T&gt; is a pull-based sequence processed in memory. When you apply .Where() or .Select() on it, the data is already in the process — LINQ-to-Objects filters it with C# lambdas. All records must be fetched before any filtering happens. IQueryable&lt;T&gt; extends IEnumerable&lt;T&gt; with an Expression tree and a query provider. LINQ operators on an IQueryable build a query description rather than executing immediately. When you enumerate (via foreach , ToList() , etc.), the provider translates the expression tree to a native query — SQL for EF Core, OData for Azure, and so on — and executes it at the source. IEnumerable: processes data in C# memory after fetching it all IQueryable: builds an expression tree, translates to native query (e.g. SQL), filters at the source Callin"
  },
  {
    "id": "attributes",
    "title": "Attributes",
    "category": "",
    "tagline": "Attach declarative metadata that tools or the runtime can read.",
    "keywords": "Attributes attach metadata to a type, method, or property without changing its behavior directly — [Obsolete] , [Serializable] , and validation attributes like [Required] are all built-in examples. The compiler understands some attributes directly; others are read by libraries or your own code via reflection. A custom attribute is simply a class that derives from System.Attribute . Attributes describe code; they don’t run unless something reads them via reflection Built-in attributes like [Obsolete] are understood directly by the compiler A custom attribute is just a class deriving from System.Attribute Applying attributes without understanding their actual effect — many require framework support to do anything Forgetting AttributeUsage — without it, the attribute can be applied anywhere, "
  },
  {
    "id": "reflection",
    "title": "Reflection",
    "category": "",
    "tagline": "Inspect and invoke types at runtime, not just compile time.",
    "keywords": "Reflection (in the System.Reflection namespace) lets code examine assemblies, types, and members — and invoke methods or set properties — at runtime, even ones it didn't know about at compile time. It's the mechanism behind serializers, dependency injection containers, and ORMs like Entity Framework. It's powerful but comes with real costs: it's slower than direct calls, bypasses some compile-time safety, and can complicate trimming/AOT-compiled apps — so it's typically reached for in framework code, not everyday application logic. typeof(T) or obj.GetType() gets a Type object describing a type's shape GetProperties/GetMethods enumerate members; Invoke calls them dynamically Powers frameworks (DI, serializers, ORMs) but is slower than direct calls Using reflection in performance-sensitive "
  },
  {
    "id": "regular-expressions",
    "title": "Regular Expressions",
    "category": "",
    "tagline": "Pattern-match and extract text with the Regex class.",
    "keywords": "The System.Text.RegularExpressions namespace exposes the Regex class for pattern matching: testing whether a string matches a pattern, extracting captured groups, or replacing matched text. Since .NET 7, the [GeneratedRegex] source generator can produce a compiled, AOT-friendly regex at build time instead of parsing the pattern at runtime — faster for patterns used repeatedly, such as validating input in a hot path. Regex.IsMatch tests, Match/Matches extract, Regex.Replace substitutes Named groups (?<year>\\d{4}) make extracted captures easier to read [GeneratedRegex] compiles the pattern at build time for better performance Using catastrophic backtracking patterns — nested quantifiers on overlapping character classes can hang the process Recompiling a Regex on every call — use a static [Ge"
  },
  {
    "id": "clean-architecture",
    "title": "Clean Architecture",
    "category": "",
    "tagline": "Organise code in layers where dependencies only point inward.",
    "keywords": "Clean Architecture (Robert C. Martin) organises a codebase into concentric layers — Domain at the centre (entities, value objects, domain logic), Application around it (use cases, interfaces), Infrastructure outside (database, email, HTTP clients), and Presentation at the edge (API controllers, Razor pages). The dependency rule : nothing in an inner layer ever references an outer one. This means your domain and application logic — the code that actually matters — has zero dependency on ASP.NET Core, Entity Framework, or any other framework. It can be tested with plain unit tests, and the infrastructure can be swapped without touching business logic. In .NET this is typically implemented with separate projects: Domain , Application , Infrastructure , and API . Dependencies point inward — Do"
  },
  {
    "id": "performance-tips",
    "title": "Performance Tips",
    "category": "",
    "tagline": "Measure first, then apply the right tool — most performance gains come from a handful of patterns.",
    "keywords": "Performance in .NET nearly always starts with measurement : BenchmarkDotNet for micro-benchmarks, dotnet-trace or Visual Studio's profiler for application-level profiling. Guessing without data wastes effort and risks making things worse. The highest-leverage patterns: avoid allocations in hot paths (use Span&lt;T&gt; , ArrayPool&lt;T&gt; , StringBuilder ); prefer async/await for I/O so threads aren't blocked; use Parallel.ForEach or PLINQ only for CPU-bound work; avoid async void , unnecessary Task.Result , and Thread.Sleep ; and keep LINQ chains over large sets out of hot paths — they allocate enumerators and delegates. ValueTask instead of Task avoids allocations when a result is often available synchronously. Profile before optimising — BenchmarkDotNet and dotnet-trace show where time "
  },
  {
    "id": "span",
    "title": "Span<T> & Memory<T>",
    "category": "",
    "tagline": "A stack-only slice over contiguous memory — zero allocation, zero copying.",
    "keywords": "Span&lt;T&gt; is a ref struct that represents a contiguous region of arbitrary memory — an array, a stack allocation, or unmanaged memory — without copying it. Because it is a ref struct, it lives only on the stack and cannot be stored in a class field, boxed, or used across await boundaries. ReadOnlySpan&lt;T&gt; is the read-only counterpart. string exposes an implicit conversion to ReadOnlySpan&lt;char&gt; , which enables zero-allocation string parsing. Memory&lt;T&gt; is the heap-safe sibling that can be stored in fields and used across async boundaries — at the cost of slightly more overhead. Span<T> is a ref struct — stack-only; cannot be stored in class fields or used across await ReadOnlySpan<char> enables zero-allocation string slicing: no substring allocation stackalloc can produc"
  },
  {
    "id": "expression-trees",
    "title": "Expression Trees",
    "category": "",
    "tagline": "Represent a lambda as a data structure you can inspect, rewrite, or compile at runtime.",
    "keywords": "When you assign a lambda to a Func&lt;T,bool&gt; , the compiler generates IL that runs the function. When you assign the same lambda to Expression&lt;Func&lt;T,bool&gt;&gt; , the compiler instead generates an expression tree — a data structure describing the lambda's AST: nodes for parameters, binary operations, member accesses, method calls. This tree can be inspected (visitor pattern), rewritten (e.g. swap a parameter), compiled to a delegate with .Compile() , or handed to a query provider that translates it to SQL, OData, or another language. EF Core's LINQ-to-SQL works entirely through expression trees. Expression<Func<T,bool>> holds a parse tree; Func<T,bool> holds compiled IL Call .Compile() to turn an expression tree into a runnable delegate ExpressionVisitor lets you walk and rewri"
  },
  {
    "id": "source-generators",
    "title": "Source Generators",
    "category": "",
    "tagline": "Emit C# source code at compile time — replace runtime reflection with generated code.",
    "keywords": "Source generators are compiler extensions (implementing IIncrementalGenerator ) that run during the build. They receive the current compilation's syntax trees and symbols, and can add new source files to the compilation — files the compiler then compiles alongside your own code. The key benefit: generated code is compiled once, type-safe, and runs at full speed without any runtime reflection. System.Text.Json 's source generator produces a serialiser for your types at build time, making JSON ~2–4× faster than reflection-based serialisation. Microsoft.Extensions.Logging 's source generator produces strongly-typed log methods that avoid boxing arguments. Generators run at compile time — output is ordinary C# that is compiled with your project IIncrementalGenerator is the modern API (prefer o"
  },
  {
    "id": "async-await",
    "title": "async / await",
    "category": "",
    "tagline": "Non-blocking code that reads like synchronous code.",
    "keywords": "Marking a method async lets you use await inside it to pause execution until a Task completes — without blocking the calling thread. This is essential for I/O-bound work like network calls or file access, where blocking a thread while waiting would waste resources. An async method typically returns Task or Task&lt;T&gt; rather than void , so callers can await it and observe exceptions properly. await frees the thread while waiting, it does not block it Async methods should return Task or Task<T>, avoid async void Exceptions inside an async method surface when the Task is awaited async void — exceptions are unobservable and crash the process; always use async Task Blocking on async code with .Result or .Wait() — deadlocks in contexts with a synchronisation context Forgetting to await a Task"
  },
  {
    "id": "tpl",
    "title": "Task Parallel Library",
    "category": "",
    "tagline": "Running independent work concurrently.",
    "keywords": "Task.WhenAll runs multiple independent async operations concurrently and completes once they all finish — much faster than awaiting them one at a time when they don't depend on each other. Use Task.Run to offload CPU-bound work onto a background thread pool thread; use plain async/await (no Task.Run) for I/O-bound work, since it doesn't need a dedicated thread while waiting. Task.WhenAll runs independent tasks concurrently, not sequentially Task.Run is for CPU-bound work; plain async/await suits I/O-bound work Awaiting tasks one-by-one in a loop loses the concurrency benefit Using Task.Run for I/O-bound work — it wastes a thread; use async/await instead Not handling exceptions from tasks — unobserved task exceptions used to crash the process (still can in some configs) Overusing Parallel.F"
  },
  {
    "id": "threading-basics",
    "title": "Threading Basics",
    "category": "",
    "tagline": "Shared state needs coordination.",
    "keywords": "When multiple threads write to shared state, you need synchronization to avoid race conditions — two threads reading-then-writing the same variable can lose an update. The lock keyword ensures only one thread executes a block at a time. For simple counters, Interlocked operations are faster than a full lock, performing the increment atomically at the hardware level. lock prevents two threads from entering the same block simultaneously Interlocked.Increment is a lightweight atomic alternative for simple counters Unsynchronized shared state is a common source of subtle, hard-to-reproduce bugs Accessing shared state from multiple threads without synchronisation — data races cause silent corruption Using Thread.Sleep for timing — it blocks the thread; use Task.Delay in async code Creating thre"
  },
  {
    "id": "cancellation-token",
    "title": "CancellationToken",
    "category": "",
    "tagline": "Cooperative cancellation for long-running or async work.",
    "keywords": "A CancellationToken lets calling code signal \"stop what you're doing\" to an async operation, without forcibly killing a thread. The running code checks the token periodically — or passes it to another cancellable API like Task.Delay — and exits cleanly when cancellation is requested, typically by throwing an OperationCanceledException . Cancellation is cooperative : nothing stops automatically unless the running code actually checks the token. Cancellation is cooperative — the running code must check the token itself CancellationTokenSource creates the token and triggers cancellation Passing the token into Task.Delay, HTTP calls, etc. lets .NET APIs cancel themselves for you Not passing the CancellationToken to every async call in the chain — cancellation won't propagate Catching Operation"
  },
  {
    "id": "async-streams",
    "title": "IAsyncEnumerable & Async Streams",
    "category": "",
    "tagline": "await foreach over a sequence produced asynchronously, one item at a time.",
    "keywords": "IAsyncEnumerable&lt;T&gt; combines yield return with async , letting a method produce items one at a time where producing each item involves an async operation, like a paged API call. The consumer uses await foreach to process each item as it arrives, instead of waiting for the entire sequence to be ready first. This is ideal for streaming results without loading everything into memory up front. Declared as async IAsyncEnumerable<T> and uses yield return inside Consumed with await foreach, not a plain foreach Ideal for streaming results (e.g. paged API responses) instead of loading everything into memory first Forgetting await before foreach when consuming an IAsyncEnumerable — won't compile, but the error message is confusing Not passing CancellationToken to the async stream — use WithCan"
  },
  {
    "id": "semaphore-slim",
    "title": "SemaphoreSlim",
    "category": "",
    "tagline": "Limit concurrency to a fixed number of workers.",
    "keywords": "While lock allows only one thread in at a time, SemaphoreSlim allows a configurable number of concurrent callers — useful for throttling access to a limited resource, like capping how many HTTP requests run in parallel. Unlike lock , it has an async-friendly WaitAsync() that doesn't block a thread while waiting, making it the right choice for throttling concurrent async work rather than raw multithreading. SemaphoreSlim(n) allows up to n concurrent callers through Wait/WaitAsync WaitAsync() doesn't block a thread, unlike lock — ideal for async throttling Always Release() in a finally block to avoid permanently starving other callers Forgetting Release() in the success path — the semaphore count never recovers, eventually starving all callers Not using try/finally around WaitAsync — an exce"
  },
  {
    "id": "channels",
    "title": "Channels",
    "category": "",
    "tagline": "A thread-safe queue built for async producer/consumer code.",
    "keywords": "System.Threading.Channels provides Channel&lt;T&gt; , an async-first queue for passing data between a producer and one or more consumers without manual locking. A writer calls WriteAsync , and a reader awaits items with ReadAllAsync , which naturally backs off when the channel is empty. Bounded channels can also apply backpressure — if the channel is full, WriteAsync waits, which keeps a fast producer from overwhelming a slower consumer. Channel<T> is a thread-safe, async-friendly producer/consumer queue ReadAllAsync() as an await foreach consumes items as they arrive Bounded channels apply backpressure, pausing writers when the buffer is full Not completing the writer — ReadAllAsync waits forever if Complete() is never called Ignoring the return value of TryWrite on a bounded channel — it"
  },
  {
    "id": "valuetask",
    "title": "ValueTask",
    "category": "",
    "tagline": "A value-type Task that avoids heap allocation when the result is already available.",
    "keywords": "Task&lt;T&gt; is a class — every async method that returns one allocates a Task object on the heap, even if the result was available synchronously (e.g. from a cache). ValueTask&lt;T&gt; is a struct that wraps either a result (no allocation) or a real Task (one allocation, same as before). When the path is synchronous, it returns with zero heap allocation. The trade-off: ValueTask has strict usage rules. It must be awaited exactly once, cannot be awaited multiple times, and should not be stored and awaited later. Violating these rules causes undefined behaviour. It also adds slightly more complexity to read. Use it only where profiling shows allocation pressure in a hot async path. ValueTask<T> avoids heap allocation when the result is synchronously available Must be awaited exactly once —"
  },
  {
    "id": "records",
    "title": "Records",
    "category": "",
    "tagline": "Immutable, value-based data types with almost no boilerplate.",
    "keywords": "A record is designed for modeling immutable data. It gets value-based equality (two records are equal if their properties match, unlike classes which compare references), a generated ToString() , and a compact constructor syntax for free. with expressions create a modified copy without mutating the original — useful for immutable update patterns common in functional-style code. Records compare by value, classes compare by reference by default with expressions produce a copy with specific properties changed Best suited to data that represents a snapshot rather than a mutable entity Mutating a record through a property with a public set — records are value-semantic by convention, not enforcement Using records for entities with identity (database rows) — records compare by value, not by id Fo"
  },
  {
    "id": "pattern-matching",
    "title": "Pattern Matching",
    "category": "",
    "tagline": "Testing shape and structure, not just equality.",
    "keywords": "Pattern matching goes beyond checking if a value equals something — it can test a value's type , its properties , and its shape all in one expression. Combined with switch expressions, this replaces a lot of nested if/else type-checking code. Property patterns (matching on an object's field values) and relational patterns (&lt;, &gt;=, etc.) can be combined for expressive, readable conditions. Type patterns test and cast in a single step: obj is string s Property patterns match on an object’s field values directly Combines cleanly with switch expressions for multi-branch logic Using patterns in if-chains instead of switch expressions when all cases are known — switch expressions are exhaustive and cleaner Forgetting that when guards run after the pattern matches — the variable is in scope "
  },
  {
    "id": "nullable-reference-types",
    "title": "Nullable Reference Types",
    "category": "",
    "tagline": "Letting the compiler catch null-reference bugs before runtime.",
    "keywords": "With nullable reference types enabled (the default in new projects), string means \"never null\" while string? explicitly allows null. The compiler then warns you at build time if you dereference something that could be null without checking first. This doesn't add a runtime check — it's a compile-time analysis that turns a common source of NullReferenceException crashes into a build warning you see immediately. string means non-null, string? means nullable, once the feature is enabled Purely a compile-time warning system, not a runtime guard Enabled by default in new project templates since .NET 6 Suppressing warnings with ! without understanding why the compiler thinks something could be null Enabling nullable in a project that doesn't have null guards everywhere — a flood of warnings that"
  },
  {
    "id": "file-scoped-namespaces",
    "title": "File-Scoped Namespaces",
    "category": "",
    "tagline": "One namespace per file, without an extra indentation level (C# 10).",
    "keywords": "A file-scoped namespace declaration ( namespace MyApp.Models; ) applies to the entire file without needing braces or an extra indent level for every type inside it. Since most files only declare one namespace anyway, this removes a layer of purely cosmetic nesting from nearly every C# file in a typical project. It behaves identically to the traditional braced form — this is a formatting improvement, not a new capability. namespace Foo; (with a semicolon, no braces) applies to the whole file Only one file-scoped namespace is allowed per file Purely a formatting improvement — behaves identically to the braced form Mixing file-scoped and block-scoped namespaces in the same project — pick one style and stick to it Using file-scoped namespaces in a file with multiple namespaces — not allowed; o"
  },
  {
    "id": "raw-string-literals",
    "title": "Raw String Literals",
    "category": "",
    "tagline": "Embed quotes and backslashes without escaping (C# 11).",
    "keywords": "A raw string literal , delimited by three or more double quotes, lets you embed characters like \" and \\ literally, with no escape sequences needed — especially useful for JSON, regex patterns, and file paths. Combine it with $ for a raw interpolated string ( $\"\"\"...\"\"\" ) to get all the benefits of interpolation without fighting escape characters. Delimited by three or more consecutive double quotes Contents are taken completely literally — no escaping needed for \" or \\\\ Combine with $ for raw interpolated strings: $\"\"\"...{expr}...\"\"\" Not reading the compiler warning before suppressing it — warnings usually point to a real problem Writing the feature before writing a test — makes it much harder to test later Ignoring null return values from framework methods — check the documentation for wh"
  },
  {
    "id": "generic-math",
    "title": "Generic Math",
    "category": "",
    "tagline": "Write one algorithm that works across every numeric type (C# 11).",
    "keywords": "Static abstract interface members let an interface declare a static member — including an operator — that every implementing type must provide. .NET's built-in numeric types ( int , double , decimal ...) all implement INumber&lt;T&gt; , so a single generic method constrained to INumber&lt;T&gt; works identically whether it's summing ints, doubles, or decimals. This removes the old need to duplicate numeric algorithms per type, or fall back to a slower, non-generic shared base type like double . Static abstract members on an interface can be operators, not just regular methods All built-in numeric types implement INumber<T> and related interfaces Removes the old need to duplicate numeric algorithms per type Not reading the compiler warning before suppressing it — warnings usually point to a"
  },
  {
    "id": "init-only-properties",
    "title": "Init-Only Properties",
    "category": "",
    "tagline": "Settable during construction, read-only ever after.",
    "keywords": "An init accessor, introduced in C# 9, works like set but can only be called during object initialization — in the constructor or an object initializer. After that, the property is effectively read-only. This gives you the convenience of object-initializer syntax while still producing genuinely immutable objects, which is exactly what the compiler generates for you automatically in a record 's positional properties. init behaves like set, but only inside a constructor or object initializer Combines object-initializer syntax with true post-construction immutability Records use init-only properties under the hood for their positional parameters Trying to set an init property after the object initializer — compiler error, but sometimes surprises people Using init when you actually need a mutab"
  },
  {
    "id": "top-level-statements",
    "title": "Top-Level Statements",
    "category": "",
    "tagline": "Skip the boilerplate Main method and class wrapper.",
    "keywords": "Top-level statements , introduced in C# 9, let a program's entry point be written directly in a file without an explicit class Program or static void Main — the compiler generates them for you behind the scenes. This is what new console and minimal-API ASP.NET Core projects use by default. Only one file per project may contain top-level statements, and command-line arguments are still available through the implicit args variable. It's purely a readability convenience — the compiled output is identical to the traditional form. The compiler generates the Main method and Program class implicitly Only one file in a project can use top-level statements args and async Main (via top-level await) both still work as expected Thinking top-level statements remove all structure — there's still an impl"
  },
  {
    "id": "primary-constructors",
    "title": "Primary Constructors",
    "category": "",
    "tagline": "Declare constructor parameters right in the class header.",
    "keywords": "Primary constructors , previously exclusive to records, are available on any class or struct since C# 12. Parameters declared in the type header are in scope throughout the whole class body — not just in field initializers — so you can use them directly in methods without assigning them to fields first. Unlike a record's primary constructor, these parameters don't automatically become public properties — if you want that, you still assign them explicitly. Available for classes and structs since C# 12, not only records Parameters are in scope for the whole class body, not just field initializers Parameters aren’t automatically properties unless you assign them explicitly Capturing a mutable parameter and modifying it — the same parameter is shared across all uses in the class Using primary "
  },
  {
    "id": "collection-expressions",
    "title": "Collection Expressions",
    "category": "",
    "tagline": "One bracket syntax for building any collection type.",
    "keywords": "Collection expressions let you write [1, 2, 3] to build an array, a List&lt;T&gt; , a Span&lt;T&gt; , or any type with a compatible construction pattern — replacing the mix of new[] { } and new List&lt;T&gt; { } syntax with one consistent form. The spread operator ( .. ) inlines the contents of another collection into a new one, similar to spread syntax in JavaScript. One bracket syntax works across arrays, List<T>, Span<T>, and more The spread operator .. inlines another collection’s elements The compiler infers the target type from context, like target-typed new Using collection expressions where the target type is ambiguous — the compiler needs to infer the type Assuming spread (..) copies deeply — it's a shallow spread, nested references are shared Mixing collection expressions with LI"
  },
  {
    "id": "required-members",
    "title": "Required Members",
    "category": "",
    "tagline": "Force callers to set specific properties at construction time.",
    "keywords": "The required modifier on a property means an object initializer must set that property, or the code simply won't compile. This closes a long-standing gap — previously the only way to guarantee a property was set was a constructor parameter, which didn't compose well with object initializer syntax. It pairs naturally with init : the property must be set once at construction, and can't be changed after that. Enforced at compile time, not runtime Pairs naturally with init so the property stays immutable after construction Lets you use object initializer syntax while still guaranteeing key properties are set Marking a property required but providing a default value — the default is ignored if required is not satisfied Using required on a property with a private setter — callers can't set it, s"
  },
  {
    "id": "params-collections",
    "title": "Params Collections",
    "category": "",
    "tagline": "params now works with Span<T>, List<T>, and more, not just arrays.",
    "keywords": "Before C# 13, params only accepted an array, which meant every call implicitly allocated a new array on the heap. C# 13 allows any recognized collection type, including Span&lt;T&gt; and ReadOnlySpan&lt;T&gt; , letting the compiler avoid that allocation for the common case of passing a handful of values. Callers don't need to change anything — the call site looks identical either way. params ReadOnlySpan<T> avoids the array allocation params T[] always required Call sites look identical — callers don’t need to change anything IEnumerable<T>, List<T>, and other collection types are supported too Not reading the compiler warning before suppressing it — warnings usually point to a real problem Writing the feature before writing a test — makes it much harder to test later Ignoring null return "
  },
  {
    "id": "field-keyword",
    "title": "The field Keyword",
    "category": "",
    "tagline": "Add logic to one accessor without a manual backing field.",
    "keywords": "The field contextual keyword lets you reach the compiler-generated backing field of an auto-property directly inside its accessors. That means you can add validation or normalization to just one accessor without declaring a private backing field and converting the whole thing into a full property. If a type already has a member literally named field , you can disambiguate with @field or this.field . field refers to the compiler-synthesized backing field — no manual field declaration needed You can add logic to just get or just set, leaving the other as a plain auto-accessor Use @field or this.field if the type already has a member literally named field Not reading the compiler warning before suppressing it — warnings usually point to a real problem Writing the feature before writing a test"
  },
  {
    "id": "null-conditional-assignment",
    "title": "Null-Conditional Assignment",
    "category": "",
    "tagline": "Use ?. on the left side of an assignment.",
    "keywords": "Before C# 14, safely assigning to a property on a possibly-null object required an explicit if check first. Null-conditional assignment lets you write customer?.Name = \"Guest\" directly — the right-hand side is only evaluated and assigned when the receiver isn't null, and the whole statement is a no-op otherwise. It also works with compound assignment operators like += and -= , though not with ++ or -- . Works with compound assignment too, e.g. += and -= Not supported for ++ or -- The right-hand expression isn’t evaluated at all when the receiver is null Using ??= when you actually want to overwrite existing values — ??= only assigns if the left side is null Forgetting that ??= is not atomic — it's not thread-safe without additional synchronisation Chaining ??= with side-effectful right-han"
  },
  {
    "id": "extension-members",
    "title": "Extension Members",
    "category": "",
    "tagline": "Extension blocks add static and instance properties, not just methods.",
    "keywords": "Traditional extension methods could only add instance methods to an existing type. C# 14 introduces a new extension block syntax that also supports extension properties and static extension members, letting you extend a type more fully without modifying its original definition. Existing this -parameter extension methods you've already written keep working exactly as before — this is purely additive. Extension blocks group multiple extension members together for a type Supports instance and static properties, in addition to methods Existing this-parameter extension methods still work exactly as before Defining extension members in the wrong namespace — callers must use the right namespace to see them Overloading an extension method with the same signature as an instance method — instance me"
  },
  {
    "id": "lock-object",
    "title": "The Lock Object",
    "category": "",
    "tagline": "A purpose-built Lock type replaces locking on a plain object.",
    "keywords": "C# 13 introduces System.Threading.Lock , a dedicated type for mutual exclusion that the lock statement now recognizes specially, generating more efficient code than locking on an ordinary object. Existing code that locks on a plain object still compiles and works exactly the same way — this is an opt-in improvement, not a breaking change. lock (System.Threading.Lock) generates more efficient code than lock (object) Existing lock (object) code keeps working unchanged Purely a performance/clarity improvement to an existing, familiar pattern Using a public or externally-visible object as the lock target — external code can deadlock your class Locking on this or the type itself — same problem as above Holding a lock while doing I/O or calling unknown code — causes deadlocks or starvation"
  },
  {
    "id": "singleton",
    "title": "Singleton",
    "category": "",
    "tagline": "Guarantee exactly one instance exists.",
    "keywords": "The Singleton pattern ensures a class has only one instance and gives global access to it — commonly used for things like configuration or logging where multiple instances would be wasteful or inconsistent. In modern C#, this is usually implemented with a static readonly field, or delegated entirely to a dependency injection container registering the service as \"singleton\" lifetime. A private constructor prevents outside code from creating more instances Static readonly fields are initialized once, thread-safely, by the runtime In ASP.NET Core apps, DI containers manage singleton lifetime for you Implementing Singleton without thread safety — two threads can create two instances simultaneously Singleton holding mutable state in an ASP.NET app — it's shared across all requests and users Usi"
  },
  {
    "id": "factory",
    "title": "Factory",
    "category": "",
    "tagline": "Centralize object creation logic.",
    "keywords": "The Factory pattern moves the decision of *which concrete type to create* into one place, so calling code depends only on an interface or base type, not a specific implementation. This makes it easy to add new types later without touching the calling code. It's especially useful when construction involves branching logic (based on config, input, or environment) that would otherwise be duplicated everywhere an object is created. Calling code depends on the abstraction, not the concrete class Centralizes branching creation logic in a single method Adding a new variant means changing the factory only, not every call site Returning concrete types from a factory instead of an interface — defeats the purpose of abstracting construction Overcomplicating a factory when a constructor with optional "
  },
  {
    "id": "observer",
    "title": "Observer",
    "category": "",
    "tagline": "One-to-many notification without tight coupling.",
    "keywords": "The Observer pattern lets one object (the subject) notify many dependent objects (observers) when its state changes, without the subject knowing anything concrete about them. C#'s built-in event keyword is a direct, language-level implementation of this pattern. This decouples the source of a change from whatever needs to react to it — the publisher never needs a reference to the subscriber's type. The subject holds no reference to concrete observer types, only the event C# events are effectively Observer built into the language Any number of observers can subscribe or unsubscribe at runtime Not unsubscribing observers when they're done — keeps them alive and receiving events indefinitely Making the event handler do expensive synchronous work — blocks the publisher and all other observers "
  },
  {
    "id": "strategy",
    "title": "Strategy",
    "category": "",
    "tagline": "Swap an algorithm at runtime behind a shared interface.",
    "keywords": "The Strategy pattern defines a family of interchangeable algorithms behind a common interface, letting you select or swap the algorithm at runtime rather than hardcoding one path with conditionals. In C#, this often collapses into simply passing a Func&lt;T,TResult&gt; delegate instead of defining a full interface with multiple implementing classes — a lightweight version of the same idea. Encapsulates interchangeable algorithms behind one interface Lets you choose the algorithm at runtime, e.g. from configuration Can be implemented with a full interface, or simply a Func<T,TResult> delegate Using Strategy when a simple if/else or switch covers all cases and never changes Making strategy objects stateful — strategies should be stateless and interchangeable Not injecting the strategy via DI"
  },
  {
    "id": "repository",
    "title": "Repository",
    "category": "",
    "tagline": "Abstract data access behind a collection-like interface.",
    "keywords": "The Repository pattern puts a collection-like interface ( GetById , Add , GetAll ) in front of your actual data source — a database, an API, or an in-memory store — so the rest of your application doesn't know or care which one it's talking to. This is what makes unit testing business logic possible without a real database: you inject an in-memory fake repository during tests, and the real EF Core-backed one in production. Business logic depends on IRepository<T>, never a concrete database class Swap in a fake/in-memory implementation for fast unit tests Commonly paired with dependency injection to supply the right implementation Not reading the compiler warning before suppressing it — warnings usually point to a real problem Writing the feature before writing a test — makes it much harder"
  },
  {
    "id": "builder",
    "title": "Builder",
    "category": "",
    "tagline": "Construct a complex object step by step.",
    "keywords": "The Builder pattern separates the construction of a complex object from its final representation, letting you assemble it through a series of chained method calls instead of one enormous constructor. It shines when an object has many optional configuration options, most of which have sensible defaults. Each builder method typically returns the builder itself, enabling method chaining , and a final Build() call produces the fully configured object. Each builder method typically returns the builder itself, enabling method chaining Avoids constructors with a long list of optional parameters A final Build() call produces the fully configured, often immutable, object Not reading the compiler warning before suppressing it — warnings usually point to a real problem Writing the feature before writ"
  },
  {
    "id": "decorator",
    "title": "Decorator",
    "category": "",
    "tagline": "Wrap an object to add behavior without changing its class.",
    "keywords": "The Decorator pattern wraps an object in another object implementing the same interface, adding behavior before or after delegating to the wrapped instance. Decorators can be stacked , letting you compose behavior — logging, caching, retry logic — without a combinatorial explosion of subclasses for every combination. The key requirement: the decorator implements the exact same interface as the thing it wraps, so callers can't tell the difference. The decorator implements the same interface as the object it wraps Multiple decorators can be layered on top of each other Avoids a separate subclass for every combination of optional behavior Decorating a type you don't own without an interface in common — use an adapter or wrapper instead Stacking many decorators and forgetting which order they "
  },
  {
    "id": "adapter",
    "title": "Adapter",
    "category": "",
    "tagline": "Make an incompatible interface fit the one you need.",
    "keywords": "The Adapter pattern wraps an existing class behind a new interface so it can be used where that interface is expected, without modifying the original class. It's the classic fix for plugging a third-party or legacy API into code written against your own abstraction. Unlike Decorator, which adds behavior while keeping the same interface, Adapter's job is purely translation — converting one shape of API into another. Adapter translates one interface into another without changing the original Common when integrating a third-party or legacy class into your own abstraction Differs from Decorator, which adds behavior rather than changing the interface Creating an adapter when you could change the original class — adapters add indirection; prefer direct changes when possible Making the adapter do"
  },
  {
    "id": "command",
    "title": "Command",
    "category": "",
    "tagline": "Turn a request into an object you can queue, log, or undo.",
    "keywords": "The Command pattern wraps an action and its parameters inside an object implementing a common interface (typically a single Execute() method), decoupling the code that invokes an action from the code that knows how to perform it. Because the request is now an object, it can be queued, logged, retried, or paired with an Undo() method — this is the pattern behind menu actions, task queues, and undo/redo stacks in editors. Command wraps a request as an object with a common Execute() interface Decouples the invoker (button, queue) from the receiver that does the work Naturally supports queuing, logging, retrying, and undo/redo Commands that directly modify shared state without going through a queue or handler — loses the undo/replay benefit Making commands too coarse — one command per user act"
  },
  {
    "id": "middleware",
    "title": "Middleware Pipeline",
    "category": "",
    "tagline": "Chain request-handling components, each deciding whether to pass control forward.",
    "keywords": "In ASP.NET Core, every HTTP request passes through a middleware pipeline — an ordered chain of components, each of which can inspect the request, do work, call the next component, and then do more work on the way back out. You compose the pipeline in Program.cs using app.Use , app.Run , and app.Map . app.Use adds a middleware that calls next() to continue the chain. app.Run is a terminal middleware — it ends the pipeline there. Order matters: a middleware registered before another wraps it completely, so authentication must come before authorization, and routing before endpoint execution. Each middleware calls await next(context) to pass to the next component app.Use adds pass-through middleware; app.Run adds a terminal one Order is critical — auth, routing, and endpoint middleware must be"
  },
  {
    "id": "minimal-apis",
    "title": "Minimal APIs",
    "category": "",
    "tagline": "Build HTTP endpoints with almost no ceremony — no controllers, no attributes.",
    "keywords": "Minimal APIs , introduced in .NET 6, let you define HTTP endpoints directly in Program.cs using MapGet , MapPost , MapPut , and MapDelete — no controller classes or action-method attributes required. The route handler is just a lambda or a named method, and ASP.NET Core automatically binds parameters from the route, query string, or request body. Route groups ( app.MapGroup ) let you add a common prefix and shared middleware to a set of endpoints. For larger apps, handler methods can be organized into separate files using extension methods on WebApplication — keeping the conciseness without forcing everything into one file. MapGet/MapPost/MapPut/MapDelete register endpoints with zero boilerplate Parameters are automatically bound from route, query string, or JSON body MapGroup adds a share"
  },
  {
    "id": "authentication",
    "title": "Authentication & Authorization",
    "category": "",
    "tagline": "Authentication proves who you are; authorization decides what you can do.",
    "keywords": "Authentication in ASP.NET Core establishes the user's identity — who is making the request. Authorization uses that identity to decide whether the request is permitted. The two are always separate: you authenticate first, then authorize. Both are added as middleware in the pipeline, and order matters — UseAuthentication must come before UseAuthorization . The [Authorize] attribute (or RequireAuthorization() in Minimal APIs) protects endpoints. Policies let you express complex rules — role checks, claim requirements, or custom logic — in one named unit rather than scattering conditions across your code. UseAuthentication() and UseAuthorization() must be added in that order [Authorize] protects a controller or endpoint; [AllowAnonymous] opens it back up Policies group authorization rules by "
  },
  {
    "id": "jwt",
    "title": "JWT",
    "category": "",
    "tagline": "Stateless, self-contained tokens for authenticating API requests.",
    "keywords": "A JSON Web Token (JWT) is a compact, URL-safe string carrying claims — assertions about a user, like their id or roles — that are cryptographically signed so a server can verify them without hitting a database. It has three base64-encoded parts separated by dots: header (algorithm), payload (claims), and signature . In ASP.NET Core, the AddJwtBearer extension registers middleware that reads the Authorization: Bearer &lt;token&gt; header, validates the signature and expiry against your configured options, and populates HttpContext.User with the token's claims — making them available to authorization policies and your own code. JWTs are signed, not encrypted — never put secrets in the payload Validate issuer, audience, and expiry — all three matter for real security Short expiry (15 min) + r"
  },
  {
    "id": "background-services",
    "title": "Background Services",
    "category": "",
    "tagline": "Run long-lived work alongside your app without blocking requests.",
    "keywords": "A hosted service in ASP.NET Core implements IHostedService (or inherits BackgroundService ) and runs for the lifetime of the application — started when the host starts, stopped gracefully when it shuts down. Common uses include polling external APIs, processing a message queue, sending scheduled emails, or cleaning up old records. BackgroundService is the abstract base class that wraps IHostedService in a simpler API: you override ExecuteAsync , loop inside it (using the provided CancellationToken to detect shutdown), and the framework handles start/stop for you. Register it with AddHostedService&lt;T&gt; . BackgroundService.ExecuteAsync runs for the app's lifetime — loop and await inside it Always respect the CancellationToken so the service shuts down cleanly Register with builder.Servic"
  },
  {
    "id": "caching",
    "title": "Caching",
    "category": "",
    "tagline": "Store expensive results and return them instantly on repeat requests.",
    "keywords": ".NET offers two main in-process caching abstractions: IMemoryCache stores data in the process's memory (fast, single-server), and IDistributedCache (backed by Redis or SQL Server) shares a cache across multiple instances. Both let you set absolute and sliding expiration policies. For the common pattern of \"get from cache, or compute and store if missing\", IMemoryCache.GetOrCreate combines the lookup and write into one atomic call. The newer HybridCache (available from .NET 9) merges both tiers and protects against cache stampedes — multiple requests all computing the same value simultaneously because the cache just expired. IMemoryCache is in-process and fast; IDistributedCache (Redis) is shared across servers GetOrCreate/GetOrCreateAsync combines lookup + set in one safe call Always set e"
  },
  {
    "id": "logging",
    "title": "Logging",
    "category": "",
    "tagline": "Structured, levelled, provider-agnostic logging built into the framework.",
    "keywords": "ASP.NET Core ships with a built-in ILogger&lt;T&gt; abstraction that works with multiple providers (console, debug, EventSource, third-party like Serilog or NLog) without your code ever knowing which one is active. Inject ILogger&lt;MyClass&gt; into a constructor and call Log.Information , Log.Warning , Log.Error , etc. Prefer structured logging over string interpolation: use message templates with named placeholders ( \"Processed {Count} items\" ). Providers that support structured data (Seq, Application Insights, Elastic) store these as queryable fields rather than raw strings, making logs far easier to search and aggregate in production. ILogger<T> is the standard abstraction — inject it, never construct a logger directly Use message templates (\"User {Id} logged in\"), not string interpola"
  },
  {
    "id": "configuration",
    "title": "Configuration",
    "category": "",
    "tagline": "Read settings from JSON, environment variables, and secrets — in priority order.",
    "keywords": "ASP.NET Core's configuration system layers multiple providers on top of each other: appsettings.json , appsettings.{Environment}.json , environment variables, command-line arguments, and (in development) User Secrets. Later providers win, so an environment variable always overrides a JSON file value. Access individual values with IConfiguration[\"Key\"] , or bind an entire section to a strongly-typed class with GetSection(\"MySection\").Get&lt;MyOptions&gt;() — which pairs naturally with the Options Pattern for validation and DI-friendly access. Never hardcode connection strings or secrets — use environment variables or a secrets manager instead. Providers layer in priority order — env vars override appsettings.json by default GetSection(\"Name\").Get<T>() binds a config section to a strongly-ty"
  },
  {
    "id": "options-pattern",
    "title": "Options Pattern",
    "category": "",
    "tagline": "Bind configuration to strongly-typed classes and inject them anywhere.",
    "keywords": "The Options Pattern wraps the raw IConfiguration API in a DI-friendly, strongly-typed layer. You define a plain class (no attributes, no base class), register it with services.Configure&lt;MyOptions&gt;(config.GetSection(\"MySection\")) , then inject IOptions&lt;MyOptions&gt; where you need it. Three interfaces give different behaviours: IOptions&lt;T&gt; is a singleton — values are read once; IOptionsSnapshot&lt;T&gt; re-reads per request (scoped); IOptionsMonitor&lt;T&gt; re-reads in real-time and fires a callback when config changes. AddOptions&lt;T&gt;().ValidateDataAnnotations() adds startup validation so a missing required field fails fast, before any request hits your code. IOptions<T> is singleton; IOptionsSnapshot<T> is per-request; IOptionsMonitor<T> is live-updating ValidateDataAn"
  },
  {
    "id": "controllers",
    "title": "Controllers",
    "category": "",
    "tagline": "Controllers route HTTP requests to action methods and return structured responses.",
    "keywords": "A controller is a class that groups related HTTP endpoints. In ASP.NET Core MVC/Web API, any class decorated with [ApiController] and inheriting ControllerBase (no view support) or Controller (adds view helpers) is a controller. Routing attributes on the class and methods map URLs to action methods. [ApiController] adds three behaviours automatically: attribute routing is required, invalid ModelState returns a 400 ProblemDetails response without you checking it, and binding source parameters are inferred ( [FromBody] , [FromRoute] , etc.). ControllerBase for APIs (no views); Controller for MVC with Razor views [ApiController] auto-validates ModelState and infers binding sources Return IActionResult or ActionResult<T> — the latter preserves the type for OpenAPI Route template on class ([Rou"
  },
  {
    "id": "model-binding",
    "title": "Model Binding",
    "category": "",
    "tagline": "ASP.NET Core automatically maps HTTP request data to action parameters.",
    "keywords": "Model binding reads data from the HTTP request and populates action method parameters and properties. By default it searches in order: route values → query string → request body . With [ApiController] , complex types default to [FromBody] and simple types default to [FromRoute] or [FromQuery] . Explicit binding source attributes let you override the default: [FromBody] reads JSON from the body (one per action), [FromQuery] reads from the URL query string, [FromRoute] reads from route segments, [FromHeader] reads from HTTP headers, and [FromForm] reads from multipart/form-data. [FromBody] reads JSON/XML request body — only one [FromBody] per action [FromQuery] binds query string parameters: /products?page=2&size=10 [FromRoute] binds route segments: /products/{id} [FromHeader] binds HTTP hea"
  },
  {
    "id": "model-validation",
    "title": "Model Validation",
    "category": "",
    "tagline": "Data annotations and ModelState validate inputs declaratively before your action runs.",
    "keywords": "Model validation checks that incoming data meets your requirements before your action method executes. Add data annotation attributes to your DTO properties and ASP.NET Core validates them automatically. With [ApiController] , invalid models return a 400 ProblemDetails response before your action body runs — no if (!ModelState.IsValid) needed. For complex business rules that annotations cannot express, implement IValidatableObject on the DTO, or use a dedicated validation library like FluentValidation that integrates with the same pipeline. [Required] rejects null/empty; [Range] enforces numeric bounds; [StringLength] limits string length [EmailAddress], [Phone], [Url] validate format with built-in regex [ApiController] auto-returns 400 ValidationProblemDetails on invalid ModelState IValid"
  },
  {
    "id": "exception-handling",
    "title": "Exception Handling & ProblemDetails",
    "category": "",
    "tagline": "Middleware and ProblemDetails give your API a consistent, RFC 9457-compliant error format.",
    "keywords": "Unhandled exceptions bubble through the middleware pipeline and, by default, return a plain 500 response with no details in production. A global exception handler centralises error handling and ensures every error returns a structured ProblemDetails response — a standard JSON error format defined by RFC 9457. ProblemDetails has standard fields: type (a URI identifying the error type), title (human-readable summary), status (HTTP status code), detail (error-specific detail), and instance (the request URI). You can add custom extensions. IExceptionHandler (.NET 8+) is the clean abstraction for registering exception handlers. app.UseExceptionHandler() catches unhandled exceptions in the pipeline ProblemDetails is the standard JSON error response format (RFC 9457) IExceptionHandler (.NET 8+) l"
  },
  {
    "id": "filters",
    "title": "Filters",
    "category": "",
    "tagline": "Run logic before or after action methods without cluttering the methods themselves.",
    "keywords": "Filters are a pipeline within the MVC/Minimal API layer, running only for requests that reach an action. They are distinct from middleware: middleware operates on raw HttpContext for all requests; filters operate on action-level context and have access to model state, action arguments, and action results. Filter types run in order: Authorization → Resource → Action → Result / Exception . Action filters run both before and after the action method. Exception filters catch unhandled exceptions from the action (prefer global exception handler for broad coverage). Result filters run after the action result is produced but before it is executed (useful for adding response headers). IActionFilter: OnActionExecuting (before) and OnActionExecuted (after) the action method IResultFilter: runs after "
  },
  {
    "id": "cors",
    "title": "CORS",
    "category": "",
    "tagline": "CORS lets browsers call your API from a different origin — you control which ones.",
    "keywords": "The browser's same-origin policy blocks JavaScript from making requests to a different origin (scheme + host + port). CORS is the W3C mechanism that lets a server explicitly permit cross-origin requests by including specific response headers. Without CORS, your React/Vue/Angular frontend hosted on app.example.com cannot call your API on api.example.com . Before state-changing requests (POST, PUT, DELETE) the browser sends a preflight OPTIONS request. Your API must respond with the correct Access-Control-Allow-* headers or the browser blocks the actual request. ASP.NET Core's CORS middleware handles all of this automatically once you configure policies. UseCors() must be placed after UseRouting() and before UseAuthorization() Named policies let you apply different CORS rules to different en"
  },
  {
    "id": "rate-limiting",
    "title": "Rate Limiting",
    "category": "",
    "tagline": "Throttle requests per client to protect your API from abuse and overload.",
    "keywords": "The built-in Microsoft.AspNetCore.RateLimiting middleware (.NET 7+) provides four algorithms out of the box. Fixed window allows N requests per time window (e.g. 100 per minute). Sliding window is smoother — it divides the window into segments so bursts are spread out. Token bucket allows bursts up to a bucket size, then refills at a steady rate. Concurrency limits simultaneous in-flight requests. Rate limiters can be global, per-named-policy (applied via attribute or endpoint metadata), or per-partition — meaning you can limit per IP address, per user, or per API key, each with its own independent counter. UseRateLimiter() must be placed after UseRouting() Fixed window: simplest — N requests per period; vulnerable to boundary bursts Sliding window: smoother — spreads requests across sub-w"
  },
  {
    "id": "openapi",
    "title": "OpenAPI / Scalar",
    "category": "",
    "tagline": "Auto-generate an OpenAPI document from your endpoints — explore it with Scalar or Swagger UI.",
    "keywords": "OpenAPI (formerly Swagger) is a standard JSON/YAML description of your API's endpoints, parameters, request bodies, and responses. .NET 9 ships a built-in OpenAPI package ( Microsoft.AspNetCore.OpenApi ) that generates this document automatically from your route registrations, ActionResult&lt;T&gt; return types, and XML doc comments. The generated document can be consumed by UI tools (Scalar, Swagger UI), code generators (NSwag, Kiota), and contract-testing tools — giving frontend teams, external consumers, and API clients an always-accurate description of your API without manual maintenance. AddOpenApi() + MapOpenApi() registers the document endpoint at /openapi/v1.json Return typed ActionResult<T> or TypedResults so the schema is inferred correctly XML doc comments (///) populate summary"
  },
  {
    "id": "ef-core",
    "title": "EF Core",
    "category": "",
    "tagline": "EF Core maps your C# classes to database tables and translates LINQ to SQL.",
    "keywords": "Entity Framework Core is .NET's official ORM. You define entities (plain C# classes), a DbContext (the database session), and EF Core handles generating SQL, tracking changes, and mapping results back to objects. Queries are written as LINQ against DbSet&lt;T&gt; properties and translated to the target database dialect (SQL Server, PostgreSQL, SQLite, etc.). Migrations keep the database schema in sync with your model — dotnet ef migrations add generates a migration file from model changes, and dotnet ef database update applies it. No manual DDL scripts needed. DbContext is the unit of work and change tracker — create one per request via DI (Scoped) DbSet<T> is the queryable repository for each entity type LINQ queries are translated to SQL and executed lazily when enumerated SaveChangesAsy"
  }
];
